# Generated by Django 3.2.7 on 2021-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='الجوال'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الرابط'),
        ),
    ]
