# Generated by Django 3.2.7 on 2021-09-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category')),
                ('category_description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Service URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
