# Generated by Django 3.2.7 on 2021-09-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210911_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service', verbose_name='Image'),
        ),
    ]
