# Generated by Django 3.2.7 on 2021-09-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210912_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Category URL'),
        ),
    ]
