# Generated by Django 3.2.7 on 2021-10-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20211015_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='صورة'),
        ),
    ]
