# Generated by Django 3.2.7 on 2021-10-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=250, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='الرابط'),
        ),
    ]
