# Generated by Django 3.2.7 on 2021-12-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20211020_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الرابط'),
        ),
    ]
