# Generated by Django 3.2.7 on 2021-10-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('partner_image', models.ImageField(upload_to='partner/', verbose_name='الصورة')),
                ('partner_event', models.CharField(blank=True, max_length=200, null=True, verbose_name='رابط التغطية')),
            ],
            options={
                'verbose_name': 'شريك نجاح',
                'verbose_name_plural': 'شركاء النجاح',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider/', verbose_name='الصورة')),
                ('slider_active', models.BooleanField(default=False, verbose_name='إظهار الصورة')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'صور الشرائح',
            },
        ),
    ]
