# Generated by Django 3.2.7 on 2021-10-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protfolio_title', models.CharField(max_length=200, verbose_name='Title')),
                ('portfolio_description', models.TextField(verbose_name='Description')),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='portfolio', verbose_name='Image')),
                ('portfolio_date', models.DateField(blank=True, verbose_name='Date')),
                ('portfolio_video', models.TextField(verbose_name='YouTube Video')),
                ('portfolio_slug', models.SlugField(blank=True, null=True, verbose_name='Portfolio URL')),
            ],
        ),
    ]
