# Generated by Django 3.2.7 on 2021-10-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'عمل', 'verbose_name_plural': 'أعمالي'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_image',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_date',
            field=models.DateField(blank=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_video',
            field=models.TextField(blank=True, null=True, verbose_name='رابط المونتاج'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='protfolio_title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
    ]
