# Generated by Django 3.2.7 on 2021-10-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211015_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_slug',
        ),
    ]
