# Generated by Django 3.2.7 on 2021-10-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_images',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رابط الصور'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رابط المونتاج'),
        ),
    ]
