# Generated by Django 3.2.7 on 2021-09-26 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0004_category_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('underway', 'underway'), ('confirmed', 'confirmed'), ('completed', 'completed')], default='underway', max_length=15, verbose_name='Status')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service.service', verbose_name='Service')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
