# Generated by Django 3.2.7 on 2021-09-26 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_request',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Order Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date_service',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 26, 14, 0, 48, 111455, tzinfo=utc), verbose_name='Service Date'),
            preserve_default=False,
        ),
    ]
