# Generated by Django 3.2.7 on 2021-09-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210926_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_request',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Date'),
        ),
    ]
