# Generated by Django 3.2.7 on 2021-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211023_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('1', 'تحت الدراسة'), ('2', 'مؤكد'), ('3', 'منفذ')], default='1', max_length=15, verbose_name='الحالة'),
        ),
    ]
